### PR TITLE
customer api and customer card api test

### PR DESCRIPTION
**Pull request by ti55987**

### CODE REVIEW

**Comment by bunnyc1986** [comment]
looks like the tests are written for SDK 2.0. In SDK 2.1 the access token is removed from method parameters.

**Comment by ti55987** [comment]
@bunnyc1986  I downloaded the newest version of SDK by following your command. PTAL.

**Comment by ti55987** [comment]
@bunnyc1986 they haven't been removed

**Comment by frojasg** [comment]
@ti55987 could you rebase this please?

**Pull request closed without merging**
